/* eslint-disable react/display-name */
import React from 'react';
import {
  FiCalendar,
  FiCheckCircle,
  FiCircle,
  FiRepeat,
  FiFlag,
  FiTrash2,
  FiClipboard,
  FiPlus,
  FiChevronDown,
  FiChevronRight,
  FiTag,
  FiHelpCircle,
  FiCornerLeftUp,
  FiEye,
  FiX,
  FiLayers,
  FiEyeOff,
  FiRotateCcw,
  FiBox,
  FiSlash,
  FiCopy,
  FiMoreVertical,
  FiChevronsLeft,
  FiChevronsRight,
  FiInbox,
  FiTerminal,
  FiThumbsUp,
  FiSettings,
  FiArrowLeft,
  FiEdit,
  FiSave,
  FiRefreshCw,
  FiMoon,
  FiSun,
  FiArrowRightCircle,
  FiArrowRight,
} from 'react-icons/fi';
import {
  MdAlarm,
  MdColorLens,
  MdHourglassBottom,
  MdOutlineUnfoldLess,
  MdOutlineUnfoldMore,
  MdChecklist,
  MdSort,
  MdDragHandle,
  MdOutlineCalendarViewWeek,
  MdBlock,
  MdOutlineDeleteSweep,
} from 'react-icons/md';
import { BiSortAlt2 } from 'react-icons/bi';
import { RiBearSmileLine } from 'react-icons/ri';
import { IconType as RIconType } from 'react-icons';
import { IconType } from '../interfaces';

export const convertSVGElementToReact = (svg: React.SVGProps<SVGElement>) => (
  <>{svg}</>
);

export const Icons: Record<IconType, RIconType> = {
  inbox: FiInbox,
  todoChecked: FiCheckCircle,
  todoUnchecked: FiCircle,
  trash: FiTrash2,
  upLevel: FiCornerLeftUp,
  repeat: FiRepeat,
  due: FiFlag,
  scheduled: FiCalendar,
  note: FiClipboard,
  add: FiPlus,
  close: FiX,
  expand: FiChevronRight,
  collapse: FiChevronDown,
  expandAll: MdOutlineUnfoldMore,
  collapseAll: MdOutlineUnfoldLess,
  stale: MdHourglassBottom,
  help: FiHelpCircle,
  label: FiTag,
  project: FiBox,
  area: FiLayers,
  show: FiEye,
  hide: FiEyeOff,
  restore: FiRotateCcw,
  trashPermanent: FiSlash,
  trashSweep: MdOutlineDeleteSweep,
  calendar: FiCalendar,
  more: FiMoreVertical,
  copy: FiCopy,
  move: FiArrowRightCircle,
  reminder: MdAlarm,
  feedback: FiThumbsUp,
  terminal: FiTerminal,
  colour: MdColorLens,
  slideLeft: FiChevronsLeft,
  slideRight: FiChevronsRight,
  settings: FiSettings,
  sort: MdSort,
  sortDirection: BiSortAlt2,
  back: FiArrowLeft,
  forward: FiArrowRight,
  subtask: MdChecklist,
  flag: MdBlock,
  edit: FiEdit,
  save: FiSave,
  view: FiLayers,
  drag: MdDragHandle,
  refresh: FiRefreshCw,
  notes: FiClipboard,
  weekly: MdOutlineCalendarViewWeek,
  todos: FiCheckCircle,
  lightMode: FiSun,
  darkMode: FiMoon,
  bear: RiBearSmileLine,
};
