export const app = {
    GO_TO_PROJECT_1: 'a g 1',
    GO_TO_PROJECT_2: 'a g 2',
    GO_TO_PROJECT_3: 'a g 3',
    GO_TO_PROJECT_4: 'a g 4',
    GO_TO_PROJECT_5: 'a g 5',
    GO_TO_PROJECT_6: 'a g 6',
    GO_TO_PROJECT_7: 'a g 7',
    GO_TO_PROJECT_8: 'a g 8',
    GO_TO_PROJECT_9: 'a g 9',
    GO_TO_NEXT_PROJECT: 'a g ]',
    GO_TO_PREV_PROJECT: 'a g [',
    GO_TO_DAILY_AGENDA: 'a g d',
    GO_TO_INBOX: 'a g i',
    GO_TO_TRASH: 'a g t',
    GO_TO_UNSCHEDULED: 'a g u',
    GO_TO_COMPLETED: 'a g c',
    SHOW_SIDEBAR: 'a s s',
    HIDE_SIDEBAR: 'a s h',
    TOGGLE_SHORTCUT_DIALOG: 'a s d',
    SHOW_CREATE_PROJECT_DIALOG: 'a p s',
}
export const item = {
    EDIT_ITEM_DESC: 'i e',
    SET_SCHEDULED_DATE: 'i s',
    SET_DUE_DATE: 'i d',
    CREATE_SUBTASK: 'i k',
    COMPLETE_ITEM: 'i c',
    UNCOMPLETE_ITEM: 'i u',
    REPEAT_ITEM: 'i r',
    DELETE_ITEM: 'i x',
    UNDELETE_ITEM: 'i n',
    MOVE_ITEM: 'i m',
    TOGGLE_CHILDREN: 'i t',
    NEXT_ITEM: 'ArrowDown',
    PREV_ITEM: 'ArrowUp',
    ESCAPE: 'Escape',
    SET_ACTIVE_ITEM: ' ',
}
