export const app = {
    GO_TO_PROJECT_1: 'g 1',
    GO_TO_PROJECT_2: 'g 2',
    GO_TO_PROJECT_3: 'g 3',
    GO_TO_PROJECT_4: 'g 4',
    GO_TO_PROJECT_5: 'g 5',
    GO_TO_PROJECT_6: 'g 6',
    GO_TO_PROJECT_7: 'g 7',
    GO_TO_PROJECT_8: 'g 8',
    GO_TO_PROJECT_9: 'g 9',
    GO_TO_NEXT_PROJECT: 'g ]',
    GO_TO_PREV_PROJECT: 'g [',
    GO_TO_DAILY_AGENDA: 'g d',
    GO_TO_INBOX: 'g i',
    GO_TO_TRASH: 'g t',
    GO_TO_STALE: 'g s',
    GO_TO_UNSCHEDULED: 'g u',
    GO_TO_COMPLETED: 'g c',
    SHOW_SIDEBAR: 's s',
    HIDE_SIDEBAR: 's h',
    TOGGLE_SHORTCUT_DIALOG: 'shift+/',
    SHOW_CREATE_PROJECT_DIALOG: 'p s',
    GO_TO_SEARCH: '/',
}
export const item = {
    EDIT_ITEM_DESC: 'e',
    SET_SCHEDULED_DATE: 's',
    SET_DUE_DATE: 'd',
    CREATE_SUBTASK: 'a',
    COMPLETE_ITEM: 'c',
    UNCOMPLETE_ITEM: 'u+c',
    REPEAT_ITEM: 'r',
    DELETE_ITEM: 'x',
    UNDELETE_ITEM: 'u+x',
    MOVE_ITEM: 'm',
    TOGGLE_CHILDREN: 't',
    NEXT_ITEM: 'j',
    PREV_ITEM: 'k',
    ESCAPE: 'Escape',
    CONVERT_TO_SUBTASK: 'v',
    SET_ACTIVE_ITEM: 'f',
}
