/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as ApiTasksRouteImport } from './routes/api.tasks'
import { Route as ApiSettingsRouteImport } from './routes/api.settings'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiGoalsRouteImport } from './routes/api.goals'
import { Route as ApiAssistantRouteImport } from './routes/api.assistant'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api.tasks.$taskId'
import { Route as ApiRemindersReminderIdRouteImport } from './routes/api.reminders.$reminderId'
import { Route as ApiQuickAddParseRouteImport } from './routes/api.quick-add.parse'
import { Route as ApiQuickAddCreateRouteImport } from './routes/api.quick-add.create'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api.projects.$projectId'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api.openapi.json'
import { Route as ApiGoalsGoalIdRouteImport } from './routes/api.goals.$goalId'
import { Route as ApiAssistantMessagesRouteImport } from './routes/api.assistant.messages'
import { Route as ApiAssistantChatRouteImport } from './routes/api.assistant.chat'
import { Route as ApiTasksTaskIdUncompleteRouteImport } from './routes/api.tasks.$taskId.uncomplete'
import { Route as ApiTasksTaskIdRemindersRouteImport } from './routes/api.tasks.$taskId.reminders'
import { Route as ApiTasksTaskIdCompleteRouteImport } from './routes/api.tasks.$taskId.complete'
import { Route as ApiRemindersReminderIdSnoozeRouteImport } from './routes/api.reminders.$reminderId.snooze'
import { Route as ApiAssistantActionsDecisionRouteImport } from './routes/api.assistant.actions.decision'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsRoute = ApiGoalsRouteImport.update({
  id: '/api/goals',
  path: '/api/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiRemindersReminderIdRoute = ApiRemindersReminderIdRouteImport.update({
  id: '/api/reminders/$reminderId',
  path: '/api/reminders/$reminderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickAddParseRoute = ApiQuickAddParseRouteImport.update({
  id: '/api/quick-add/parse',
  path: '/api/quick-add/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickAddCreateRoute = ApiQuickAddCreateRouteImport.update({
  id: '/api/quick-add/create',
  path: '/api/quick-add/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsGoalIdRoute = ApiGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => ApiGoalsRoute,
} as any)
const ApiAssistantMessagesRoute = ApiAssistantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiAssistantRoute,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiAssistantRoute,
} as any)
const ApiTasksTaskIdUncompleteRoute =
  ApiTasksTaskIdUncompleteRouteImport.update({
    id: '/uncomplete',
    path: '/uncomplete',
    getParentRoute: () => ApiTasksTaskIdRoute,
  } as any)
const ApiTasksTaskIdRemindersRoute = ApiTasksTaskIdRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => ApiTasksTaskIdRoute,
} as any)
const ApiTasksTaskIdCompleteRoute = ApiTasksTaskIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiTasksTaskIdRoute,
} as any)
const ApiRemindersReminderIdSnoozeRoute =
  ApiRemindersReminderIdSnoozeRouteImport.update({
    id: '/snooze',
    path: '/snooze',
    getParentRoute: () => ApiRemindersReminderIdRoute,
  } as any)
const ApiAssistantActionsDecisionRoute =
  ApiAssistantActionsDecisionRouteImport.update({
    id: '/actions/decision',
    path: '/actions/decision',
    getParentRoute: () => ApiAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/mcp': typeof McpRoute
  '/upcoming': typeof UpcomingRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/messages': typeof ApiAssistantMessagesRoute
  '/api/goals/$goalId': typeof ApiGoalsGoalIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRoute
  '/api/quick-add/create': typeof ApiQuickAddCreateRoute
  '/api/quick-add/parse': typeof ApiQuickAddParseRoute
  '/api/reminders/$reminderId': typeof ApiRemindersReminderIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/api/assistant/actions/decision': typeof ApiAssistantActionsDecisionRoute
  '/api/reminders/$reminderId/snooze': typeof ApiRemindersReminderIdSnoozeRoute
  '/api/tasks/$taskId/complete': typeof ApiTasksTaskIdCompleteRoute
  '/api/tasks/$taskId/reminders': typeof ApiTasksTaskIdRemindersRoute
  '/api/tasks/$taskId/uncomplete': typeof ApiTasksTaskIdUncompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/mcp': typeof McpRoute
  '/upcoming': typeof UpcomingRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/messages': typeof ApiAssistantMessagesRoute
  '/api/goals/$goalId': typeof ApiGoalsGoalIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRoute
  '/api/quick-add/create': typeof ApiQuickAddCreateRoute
  '/api/quick-add/parse': typeof ApiQuickAddParseRoute
  '/api/reminders/$reminderId': typeof ApiRemindersReminderIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/api/assistant/actions/decision': typeof ApiAssistantActionsDecisionRoute
  '/api/reminders/$reminderId/snooze': typeof ApiRemindersReminderIdSnoozeRoute
  '/api/tasks/$taskId/complete': typeof ApiTasksTaskIdCompleteRoute
  '/api/tasks/$taskId/reminders': typeof ApiTasksTaskIdRemindersRoute
  '/api/tasks/$taskId/uncomplete': typeof ApiTasksTaskIdUncompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/mcp': typeof McpRoute
  '/upcoming': typeof UpcomingRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/messages': typeof ApiAssistantMessagesRoute
  '/api/goals/$goalId': typeof ApiGoalsGoalIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRoute
  '/api/quick-add/create': typeof ApiQuickAddCreateRoute
  '/api/quick-add/parse': typeof ApiQuickAddParseRoute
  '/api/reminders/$reminderId': typeof ApiRemindersReminderIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/api/assistant/actions/decision': typeof ApiAssistantActionsDecisionRoute
  '/api/reminders/$reminderId/snooze': typeof ApiRemindersReminderIdSnoozeRoute
  '/api/tasks/$taskId/complete': typeof ApiTasksTaskIdCompleteRoute
  '/api/tasks/$taskId/reminders': typeof ApiTasksTaskIdRemindersRoute
  '/api/tasks/$taskId/uncomplete': typeof ApiTasksTaskIdUncompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completed'
    | '/inbox'
    | '/mcp'
    | '/upcoming'
    | '/api/assistant'
    | '/api/goals'
    | '/api/projects'
    | '/api/settings'
    | '/api/tasks'
    | '/demo/mcp-todos'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/project/$projectId'
    | '/api/assistant/chat'
    | '/api/assistant/messages'
    | '/api/goals/$goalId'
    | '/api/openapi/json'
    | '/api/projects/$projectId'
    | '/api/quick-add/create'
    | '/api/quick-add/parse'
    | '/api/reminders/$reminderId'
    | '/api/tasks/$taskId'
    | '/demo/api/mcp-todos'
    | '/api/assistant/actions/decision'
    | '/api/reminders/$reminderId/snooze'
    | '/api/tasks/$taskId/complete'
    | '/api/tasks/$taskId/reminders'
    | '/api/tasks/$taskId/uncomplete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completed'
    | '/inbox'
    | '/mcp'
    | '/upcoming'
    | '/api/assistant'
    | '/api/goals'
    | '/api/projects'
    | '/api/settings'
    | '/api/tasks'
    | '/demo/mcp-todos'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/project/$projectId'
    | '/api/assistant/chat'
    | '/api/assistant/messages'
    | '/api/goals/$goalId'
    | '/api/openapi/json'
    | '/api/projects/$projectId'
    | '/api/quick-add/create'
    | '/api/quick-add/parse'
    | '/api/reminders/$reminderId'
    | '/api/tasks/$taskId'
    | '/demo/api/mcp-todos'
    | '/api/assistant/actions/decision'
    | '/api/reminders/$reminderId/snooze'
    | '/api/tasks/$taskId/complete'
    | '/api/tasks/$taskId/reminders'
    | '/api/tasks/$taskId/uncomplete'
  id:
    | '__root__'
    | '/'
    | '/completed'
    | '/inbox'
    | '/mcp'
    | '/upcoming'
    | '/api/assistant'
    | '/api/goals'
    | '/api/projects'
    | '/api/settings'
    | '/api/tasks'
    | '/demo/mcp-todos'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/project/$projectId'
    | '/api/assistant/chat'
    | '/api/assistant/messages'
    | '/api/goals/$goalId'
    | '/api/openapi/json'
    | '/api/projects/$projectId'
    | '/api/quick-add/create'
    | '/api/quick-add/parse'
    | '/api/reminders/$reminderId'
    | '/api/tasks/$taskId'
    | '/demo/api/mcp-todos'
    | '/api/assistant/actions/decision'
    | '/api/reminders/$reminderId/snooze'
    | '/api/tasks/$taskId/complete'
    | '/api/tasks/$taskId/reminders'
    | '/api/tasks/$taskId/uncomplete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletedRoute: typeof CompletedRoute
  InboxRoute: typeof InboxRoute
  McpRoute: typeof McpRoute
  UpcomingRoute: typeof UpcomingRoute
  ApiAssistantRoute: typeof ApiAssistantRouteWithChildren
  ApiGoalsRoute: typeof ApiGoalsRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiQuickAddCreateRoute: typeof ApiQuickAddCreateRoute
  ApiQuickAddParseRoute: typeof ApiQuickAddParseRoute
  ApiRemindersReminderIdRoute: typeof ApiRemindersReminderIdRouteWithChildren
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals': {
      id: '/api/goals'
      path: '/api/goals'
      fullPath: '/api/goals'
      preLoaderRoute: typeof ApiGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/reminders/$reminderId': {
      id: '/api/reminders/$reminderId'
      path: '/api/reminders/$reminderId'
      fullPath: '/api/reminders/$reminderId'
      preLoaderRoute: typeof ApiRemindersReminderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-add/parse': {
      id: '/api/quick-add/parse'
      path: '/api/quick-add/parse'
      fullPath: '/api/quick-add/parse'
      preLoaderRoute: typeof ApiQuickAddParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-add/create': {
      id: '/api/quick-add/create'
      path: '/api/quick-add/create'
      fullPath: '/api/quick-add/create'
      preLoaderRoute: typeof ApiQuickAddCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals/$goalId': {
      id: '/api/goals/$goalId'
      path: '/$goalId'
      fullPath: '/api/goals/$goalId'
      preLoaderRoute: typeof ApiGoalsGoalIdRouteImport
      parentRoute: typeof ApiGoalsRoute
    }
    '/api/assistant/messages': {
      id: '/api/assistant/messages'
      path: '/messages'
      fullPath: '/api/assistant/messages'
      preLoaderRoute: typeof ApiAssistantMessagesRouteImport
      parentRoute: typeof ApiAssistantRoute
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof ApiAssistantRoute
    }
    '/api/tasks/$taskId/uncomplete': {
      id: '/api/tasks/$taskId/uncomplete'
      path: '/uncomplete'
      fullPath: '/api/tasks/$taskId/uncomplete'
      preLoaderRoute: typeof ApiTasksTaskIdUncompleteRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/tasks/$taskId/reminders': {
      id: '/api/tasks/$taskId/reminders'
      path: '/reminders'
      fullPath: '/api/tasks/$taskId/reminders'
      preLoaderRoute: typeof ApiTasksTaskIdRemindersRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/tasks/$taskId/complete': {
      id: '/api/tasks/$taskId/complete'
      path: '/complete'
      fullPath: '/api/tasks/$taskId/complete'
      preLoaderRoute: typeof ApiTasksTaskIdCompleteRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/reminders/$reminderId/snooze': {
      id: '/api/reminders/$reminderId/snooze'
      path: '/snooze'
      fullPath: '/api/reminders/$reminderId/snooze'
      preLoaderRoute: typeof ApiRemindersReminderIdSnoozeRouteImport
      parentRoute: typeof ApiRemindersReminderIdRoute
    }
    '/api/assistant/actions/decision': {
      id: '/api/assistant/actions/decision'
      path: '/actions/decision'
      fullPath: '/api/assistant/actions/decision'
      preLoaderRoute: typeof ApiAssistantActionsDecisionRouteImport
      parentRoute: typeof ApiAssistantRoute
    }
  }
}

interface ApiAssistantRouteChildren {
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiAssistantMessagesRoute: typeof ApiAssistantMessagesRoute
  ApiAssistantActionsDecisionRoute: typeof ApiAssistantActionsDecisionRoute
}

const ApiAssistantRouteChildren: ApiAssistantRouteChildren = {
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiAssistantMessagesRoute: ApiAssistantMessagesRoute,
  ApiAssistantActionsDecisionRoute: ApiAssistantActionsDecisionRoute,
}

const ApiAssistantRouteWithChildren = ApiAssistantRoute._addFileChildren(
  ApiAssistantRouteChildren,
)

interface ApiGoalsRouteChildren {
  ApiGoalsGoalIdRoute: typeof ApiGoalsGoalIdRoute
}

const ApiGoalsRouteChildren: ApiGoalsRouteChildren = {
  ApiGoalsGoalIdRoute: ApiGoalsGoalIdRoute,
}

const ApiGoalsRouteWithChildren = ApiGoalsRoute._addFileChildren(
  ApiGoalsRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiTasksTaskIdRouteChildren {
  ApiTasksTaskIdCompleteRoute: typeof ApiTasksTaskIdCompleteRoute
  ApiTasksTaskIdRemindersRoute: typeof ApiTasksTaskIdRemindersRoute
  ApiTasksTaskIdUncompleteRoute: typeof ApiTasksTaskIdUncompleteRoute
}

const ApiTasksTaskIdRouteChildren: ApiTasksTaskIdRouteChildren = {
  ApiTasksTaskIdCompleteRoute: ApiTasksTaskIdCompleteRoute,
  ApiTasksTaskIdRemindersRoute: ApiTasksTaskIdRemindersRoute,
  ApiTasksTaskIdUncompleteRoute: ApiTasksTaskIdUncompleteRoute,
}

const ApiTasksTaskIdRouteWithChildren = ApiTasksTaskIdRoute._addFileChildren(
  ApiTasksTaskIdRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRouteWithChildren
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksTaskIdRoute: ApiTasksTaskIdRouteWithChildren,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

interface ApiRemindersReminderIdRouteChildren {
  ApiRemindersReminderIdSnoozeRoute: typeof ApiRemindersReminderIdSnoozeRoute
}

const ApiRemindersReminderIdRouteChildren: ApiRemindersReminderIdRouteChildren =
  {
    ApiRemindersReminderIdSnoozeRoute: ApiRemindersReminderIdSnoozeRoute,
  }

const ApiRemindersReminderIdRouteWithChildren =
  ApiRemindersReminderIdRoute._addFileChildren(
    ApiRemindersReminderIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletedRoute: CompletedRoute,
  InboxRoute: InboxRoute,
  McpRoute: McpRoute,
  UpcomingRoute: UpcomingRoute,
  ApiAssistantRoute: ApiAssistantRouteWithChildren,
  ApiGoalsRoute: ApiGoalsRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiQuickAddCreateRoute: ApiQuickAddCreateRoute,
  ApiQuickAddParseRoute: ApiQuickAddParseRoute,
  ApiRemindersReminderIdRoute: ApiRemindersReminderIdRouteWithChildren,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
